version: "3.8"

networks:
  local-network:
    driver: bridge
services:
  game:
    build:
      context: ./services/game
    expose:
      - 5000
    networks:
      - local-network
    depends_on:
      - redis
      - memegen
  celery:
    build:
      context: ./services/game
    depends_on:
      - redis
    networks:
      - local-network
  memegen:
    build:
      context: ./services/memegen
    expose:
      - 5000
    networks:
      - local-network
  nginx:
    build:
      context: ./services/nginx
      target: base
    ports:
      - 80:80
    depends_on:
      - game
    networks:
      - local-network
  redis:
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    image: redis:6.2-alpine
    expose:
      - 6379
    networks:
      - local-network

volumes:
  memes_dir:
