version: "3.8"

services:
  game:
    build:
      context: ./services/game
    restart: unless-stopped
    expose:
      - 5000
    networks:
      - app-network
    depends_on:
      - redis
      - memegen

  celery:
    build:
      context: ./services/game
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app-network

  memegen:
    build:
      context: ./services/memegen
    restart: unless-stopped
    expose:
      - 5000
    networks:
      - app-network

  nginx:
    build:
      context: ./services/nginx
      target: base
      #restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - game
    networks:
      - app-network

  redis:
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    image: redis:6.2-alpine
    expose:
      - 6379
    networks:
      - app-network


volumes:
  memes_dir:
  certbot-etc:
  certbot-var:
  certbot-web:
  dhparam:
          driver: local
          driver_opts:
                  type: none
                  device: /root/caption-this/dhparam
                  o: bind


networks:
  app-network:
    driver: bridge
