# This is a compose file for development
version: '3.8'

services:
    frontend:
        build:
            target: base
        command: python manage.py run -h 0.0.0.0 -p 5000
        env_file:
            - ./.env.dev
        volumes:
            - ./services/frontend:/usr/src/app
    game:
        build:
            target: base
        command: python manage.py run -h 0.0.0.0 -p 5000
        env_file:
            - ./.env.dev
        volumes:
            - ./services/game:/usr/src/app
    celery:
        build:
            target: base
        command: ["/bin/sh", "-c", "./celery.sh"]
        env_file:
            - ./.env.dev
    memegen:
        build:
            target: base
        command: python run.py
        volumes:
            - memes_dir:/usr/src/app/images/
        environment:
            - DEBUG=1
    nginx:
        volumes:
            - memes_dir:/usr/src/app/images/
    redis:
        ports:
            - "6379:6379"
